apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrectlyweb
  namespace: default
spec:
  selector:
    matchLabels:
      app: carrectlyweb
  replicas: 3
  strategy: 
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 50%
       maxUnavailable: 0%
  template:
    metadata:
      labels:
         app: carrectlyweb
    spec:
      containers:
        - name: carrectlyweb
          image: "<imageTag>"

---
    apiVersion: v1
    kind: Service
    metadata:
      name: carrectlyweb-service
      labels:
        app: carrectlyweb
    spec:
       ports:
        - name: carrectlyweb
          port: 3000
          targetPort: 3000
       selector:
        app: carrectlyweb

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: carrectlyweb-autoscaling 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: carrectlyweb
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70