apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: carrectlyweb-autoscaling 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: carrectlyweb
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 85