apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrectlyweb
  namespace: carrectlyweb
spec:
  selector:
    matchLabels:
      app: carrectlyweb
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
         app: carrectlyweb
    spec:
      containers:
        - name: carrectlyweb
          image: "<imageTag>"

