apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: carrectlyweb-autoscaling 
  namespace: carrectlyweb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: carrectlyweb
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75