apiVersion: v1
kind: Service
metadata:
  name: carrectlyweb
  namespace: stage-carrectlyweb
  labels:
    app: carrectlyweb
spec:
   ports:
    - name: carrectlyweb
      port: 3000
      targetPort: 3000
   selector:
    app: carrectlyweb