apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrectlyweb
  namespace: carrectlyweb
spec:
  selector:
    matchLabels:
      app: carrectlyweb
  replicas: 2
  minReadySeconds: 12
  template:
    metadata:
      labels:
         app: carrectlyweb
    spec:
      containers:
        - name: carrectlyweb
          image: "<imageTag>"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 400
            periodSeconds: 300
      restartPolicy: Always
