apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: carrectlyweb-autoscaling 
  namespace: carrectlyweb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: carrectlyweb
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu 
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
